from Seq1 import Seq

s1 = Seq("AGTACACTGGT")
s2 = Seq("ABDUYW")
s3 = Seq("")
print("s1: ", "(length:", s1.len(), ")", s1.strbases)
a = s1.count_bases("A")
t = s1.count_bases("T")
g = s1.count_bases("G")
c = s1.count_bases("C")
print(f"A: {a} T: {t} C: {c} G: {g}")
print("s2: ", "(length:", s2.len(), ")", s2.strbases)
a = s2.count_bases("A")
t = s2.count_bases("T")
g = s2.count_bases("G")
c = s2.count_bases("C")
print(f"A: {a} T: {t} C: {c} G: {g}")
print("s3: ", "(length:", s3.len(), ")", s3.strbases)
a = s3.count_bases("A")
t = s3.count_bases("T")
g = s3.count_bases("G")
c = s3.count_bases("C")
print(f"A: {a} T: {t} C: {c} G: {g}")


